### ISSUE TITLE
文節移動が見えない (27.1-rc[12])

### ISSUE THREAD

**Issue by Nyoho** [takaxp/ns-inline-patch#3]
27.1-rc[12] で27用のns-inline-patchを使うと文節を移動したときにどこにいるのかわからなくなります。
ns-marked-text-face が適切に移動してくれていない感じがいたします。
こちらでは rc1 でも rc2 でも再現しています。

### macOS Catalina の標準の日本語入力
(`C-f` して「やってみます」の部分がworkingになっている)
![image](https://user-images.githubusercontent.com/118150/89788449-230fd080-db5a-11ea-88ae-dc2a68b4f494.png)

### ATOK
(`C-f` して「入力を」の部分がworkingになっている)
![image](https://user-images.githubusercontent.com/118150/89788537-463a8000-db5a-11ea-95c8-e00bf407000a.png)

**Comment by takaxp** [comment]
報告ありがとうごいます．既知のバグです．
GoogleIMEターゲットで実装しているので，他のIMEは順次対応しております．

**Comment by Nyoho** [comment]
ありがとうございます! 既知だと知れてよかったです。
GoogleIMEでのコードが、ATOKでテストするとどうなるかなど必要に応じてやりますのでお申し付けください!

**Comment by takaxp** [comment]
助かります!!

**Comment by Nyoho** [comment]
まだ公開されてないですよね……? (あ、別ブランチ見てなかったと思って今見に行ったらやはりまだだった^^)

**Comment by takaxp** [comment]
とりあえず改善したように思いますので、しばらくしたら master に取り込んで close します。

**Comment by Nyoho** [comment]
ありがとうございます! 手元でも治りました!

![image](https://user-images.githubusercontent.com/118150/134751949-37046cd5-d273-4e3e-812d-60cf3bf1d21f.png)

![image](https://user-images.githubusercontent.com/118150/134751959-bf4a0fee-ce6f-4259-9fc9-3d54f9f7ae05.png)

**Comment by takaxp** [comment]
ご確認いただきありがとうございます!
標準IMEで、文節選択中に `(beginning-of-buffer)` などを呼び出せてしまう（C-M-tを割り振っているとかで）のがちょっとネック（カーソルが飛んで、次に日本語を打つまでおかしな事になる）なのですが、これは別途対策を考えようと思います。
